# Generated by Django 4.0.3 on 2022-03-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='token_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('problems', models.CharField(max_length=200)),
                ('drid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosapp.doctors_tb')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosapp.patient_tb')),
            ],
        ),
    ]
