# Generated by Django 4.0.3 on 2022-03-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosapp', '0005_token_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors_tb',
            name='Email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
